name: usual CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Lint with mypy
      run: |
        mypy .
    - name: Lint with black
      run: |
        black --check --line-length 79 src/
    - name: Lint with isort
      run: |
        isort --check-only --profile=black src/
